################################################################################
# dnb-hugo-giscus @see https://github.com/dnb-org/dnb-hugo-giscus
################################################################################
[dnb.giscus]
src = "https://giscus.app/client.js"
#dataRepo = "username/reponame"
#dataRepoId = "ABCDEFGHIJKLMNOPQSTUVXYZABCDEFGH"
#dataCategory = "Comments"
#dataCategoryId = "ABCDEFGHIJKLMNOPQRST"
dataMapping = "specific"
dataLoading = "lazy"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "top"  # top, bottom
dataTheme = "dark"
# de, en, es, fr, gsw, id, it, ja, ko, pl, ro, ru, tr, vi, zh-CN, zh-TW
dataLang = "en"
